[package]
name = "lzw"
version = "0.1.0"
edition = "2021"
autobenches = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bitstream-io = "1.3"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "lzw_bench"
harness = false
